version: "3.7"

services:
  mock-server:
    image: mockoon/cli:latest
    command: ["--data", "data", "--port", "3007"]
    ports:
      - 31007:3007
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3007/api/healthcheck || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - ./mockoon-mocks.json:/data:ro

